name: analysis2
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - gcc
  - gmp
  - gxx
  - mpfr
  - pip
  - slim==4.0
  - snakemake
  - ldc
  - seaborn
  - pysam
  - htslib
  - scipy
  - numpy
  - matplotlib
  - attrs
  - cython
  - tqdm
  - h5py
  - gfortran
  - blas
  - gsl
  - dadi==2.2.0
  - mamba
  - openjdk
  - sweepfinder2
  - scikit-learn
  - r-base
  - r-essentials
  - r-irkernel
  - r-ggplot2
  - r-dplyr
  - r-patchwork
  - r-scales
  - r-ggnewscale
  - libprotobuf=3.21.12
  - pip:
    - git+https://github.com/popsim-consortium/stdpopsim.git
    - scikit-allel
    - git+https://github.com/xin-huang/dadi-cli
    - diploSHIC
