"seed": 12345
"population_id": 0
"num_samples_per_population": [100, 100, 100]
"replicates": 20
"species": "HomSap"
"demo_models": ["Constant", "OutOfAfrica_3G09"]
"genetic_map": "HapmapII_GRCh37"
"chrm_list": "chr21"
"output_dir": "results"
"poly_dfe_exec": "../ext/polyDFE/polyDFE-2.0-linux-64-bit"
